#!/bin/bash

set -e

rm -rf /home/aceccarelli/projects/dotfiles/lvim/

cp -r /home/aceccarelli/.config/lvim/ /home/aceccarelli/projects/dotfiles

cd /home/aceccarelli/projects/dotfiles/

GIT='git --git-dir='$PWD'/.git'

$GIT add .
$GIT commit --message "automatic back-up"
$GIT push

echo "Pushed automated commit"

